model_path: "AppBase/model/HexBox.obj"

windows:
  serial_port: "COM11" # stationary com is 11 but funcitoning com is 8
  serial_delay: 0.01
  baud_rate: 9600
  retries: 5
  setup_delay: 2
  # ...other settings...

linux:
  serial_port: "/dev/ttyACM0"
  serial_delay: 0.05
  baud_rate: 115200
  retries: 5
  setup_delay: 2
  # ...other settings...

tag_size: 0.05 # in meters
tag_family: "tag36h11"
model_scale: 0.05

camera_matrix:
  - [600, 0, 320]
  - [0, 600, 240]
  - [0, 0, 1]

distortion_coefficients: [0.0, 0.0, 0.0, 0.0]

base_offset_tag_frame: [-0.10, 0.00, 0.00]
base_rpy_from_tag_deg: [0.0, 0.0, 0.0]  
shoulder_z_offset_m: 0.05

translation_offset:
  x: 0.0
  y: 0.0
  z: 0.0

tag_roles:
  "1": "base"
  "3": "cont"
