model_path: "AppBase/model/HexBox.obj"

windows:
  camera_id: 0
  serial_port: "COM3"
  serial_delay: 0.01
  # ...other settings...

linux:
  camera_id: 0
  serial_port: "/dev/ttyACM0"
  serial_delay: 0.05
  # ...other settings...

tag_id: 0
tag_size: 0.05
tag_family: "tag36h11"

model_scale: 0.05

camera_matrix:
  - [600, 0, 320]
  - [0, 600, 240]
  - [0, 0, 1]

distortion_coefficients: [0.0, 0.0, 0.0, 0.0]

translation_offset:
  x: 0.0
  y: 0.0
  z: 0.0

