model_path: "AppBase/model/HexBox.obj"

windows:
  camera_id: 0 # 1 for webcam, 0 for main camera
  serial_port: "COM3"
  serial_delay: 0.01
  baud_rate: 115200
  retries: 5
  setup_delay: 2
  # ...other settings...

linux:
  camera_id: 0
  serial_port: "/dev/ttyACM0"
  serial_delay: 0.05
  baud_rate: 115200
  retries: 5
  setup_delay: 2
  # ...other settings...

valid_tag_ids: [1, 3]
tag_size: 0.05 # in meters
tag_family: "tag36h11"

model_scale: 0.05

camera_matrix:
  - [600, 0, 320]
  - [0, 600, 240]
  - [0, 0, 1]

distortion_coefficients: [0.0, 0.0, 0.0, 0.0]

translation_offset:
  x: 0.0
  y: 0.0
  z: 0.0

tag_roles:
  "1": "base"
  "3": "cont"